source:       ./_code
destination:  ./_deploy

title: 5loaves2fish
subtitle: When you want more
description: When you want more
url: http://5loaves2fish.blog
# baseurl: "/5loaves2fish"
baseurl: ""
url: "http://5loaves2fish.blog"
archive: archive

localization:
  read-more: "Read more"
  see-all-posts: "See all posts"

# Build settings
markdown: kramdown
theme: superwriter
gems:
exclude:
  - Gemfile
  - Gemfile.lock

# landing type: index | single | page
landing: index
post-per-page: 10
favicon: images/logo/logo-64x64.png
header:
  logo-img: images/logo/logo.png
  title-img: images/logo/5loaves2fish.png
  subtitle: When you want more
facebook.image:

facebook.page: https://www.facebook.com/5loaves2fish.blog

footer:
  script-note: "Crafted with <i class='fa fa-heart'></i> by <a href='http://5p2p.it'>5pani2pesci</a><br>Don't reproduce without permission."

facebook.app_id: 480155522043231
google_analytics: UA-39520577-2

# <meta property="fb:admins" content="1010218604"/>
# <meta property="fb:app_id" content="480155522043231"/>

permalink: :title/
defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"

collections:
  pages:
    output: true
    permalink: /:title/
